-- ManageMe production database note
--
-- Do not run table-creation or table-renaming migrations against the current
-- production Supabase project. The app is intentionally written to use the
-- existing tables:
--
-- - public.schedules
-- - public.todos
-- - public.routines
-- - public.routine_completions
--
-- The current React code expects routine completions to use:
--
-- - id
-- - user_id
-- - routine_id
-- - completed_date
-- - completed_at
--
-- No SQL is required for this change. Keep existing RLS policies in place so
-- each query can be constrained by auth.uid() = user_id.
